/**
 * Lista bonus / operatori — aggiorna qui per cambiare le card in homepage.
 * Ordinamento in pagina: campo `order` (crescente).
 */
window.__CASINO_BONUSES__ = [
    {
        id: '1',
        title: '250% up to $4,000 + 150 Free Spins',
        description:
            '1st Deposit:150% up to $1500  +50 FS\n2nd Deposit:50% up to $1000 +50 FS\n3rd Deposit:50% up to $1500 +50 FS.',
        code: '',
        link: 'https://mnsw.kronvax.com/?mid=366179_2112118',
        image: 'images/monsterwin.png',
        tags: ['featured'],
        rating: 5,
        exclusive: false,
        terms: '18+. T&Cs apply.',
        wagering: '35x',
        minDeposit: '30$',
        maxBonus: '',
        casino: 'Monsterwin ',
        brandName: 'Monsterwin ',
        casinoId: 'PV8jUsLbBuTl0WWCwQ7f',
        order: 0
    },
    {
        id: '3',
        title: '300% up to $4750 + 100 Free Spins',
        description:
            '1st Deposit:100% up to $2500 +100 FS l\n2nd Deposit:75% up to $1500\n3rd Deposit:125% up to $750',
        code: '',
        link: 'https://jky.kronvax.com/?mid=366184_2112119',
        image: 'images/jokery.png',
        tags: [],
        rating: 5,
        exclusive: false,
        terms: '18+. T&Cs apply.',
        wagering: '35x',
        minDeposit: '30$',
        maxBonus: '',
        casino: 'Jokery ',
        brandName: 'Jokery ',
        casinoId: 'AyEPAmEdcYXsunImU1ah',
        order: 1
    },
    {
        id: '2',
        title: '300% up to $10000 + 300 Free Spins',
        description:
            '1st Deposit:100% up to $3500  +100 FS\n2nd Deposit:100% up to $3000 +75 FS\n3rd Deposit:100% up to $3500 +125 FS.',
        code: '',
        link: 'https://csna.fynkelto.com/?mid=366185_2112120',
        image: 'images/casina.png',
        tags: ['welcome', 'exclusive'],
        rating: 5,
        exclusive: false,
        terms: '18+. T&Cs apply.',
        wagering: '35x',
        minDeposit: '30$',
        maxBonus: '',
        casino: 'Casina ',
        brandName: 'Casina ',
        casinoId: 'h8AZJxvLZOVfQjBS8fqx',
        order: 2
    },
    {
        id: '5',
        title: '250% up to $4,000 + 150 Free Spins',
        description:
            '1st Deposit:150% up to $1500  +50 FS\n2nd Deposit:50% up to $1000 +50 FS\n3rd Deposit:50% up to $1500 +50 FS.',
        code: '',
        link: 'https://qwin.virelon.com/?mid=366181_2112122',
        image: 'images/quickwin.png',
        tags: ['exclusive', 'standard'],
        rating: 5,
        exclusive: false,
        terms: '18+. T&Cs apply.',
        wagering: '35x',
        minDeposit: '30$',
        maxBonus: '',
        casino: 'Quickwin',
        brandName: 'Quickwin',
        casinoId: '3zkm0ENa5fYCmx148pjU',
        order: 3
    },
    {
        id: '4',
        title: '250% up to $4,000 + 150 Free Spins',
        description:
            '1st Deposit:150% up to $1500  +50 FS\n2nd Deposit:50% up to $1000 +50 FS\n3rd Deposit:50% up to $1500 +50 FS',
        code: '',
        link: 'https://rltz.myloric.com/?mid=366180_2112121',
        image: 'images/realz.jpg',
        tags: ['Welcome'],
        rating: 5,
        exclusive: false,
        terms: '18+. T&Cs apply.',
        wagering: '35x',
        minDeposit: '30$',
        maxBonus: '',
        casino: 'Realz ',
        brandName: 'Realz ',
        casinoId: '9jBWie2dOrywdYzBW6UA',
        order: 4
    },
    {
        id: '6',
        title: '250% up to $4,000 + 150 Free Spins',
        description:
            '1st Deposit:150% up to $1500  +50 FS\n2nd Deposit:50% up to $1000 +50 FS\n3rd Deposit:50% up to $1500 +50 FS.',
        code: '',
        link: 'https://scd.kronvax.com/?mid=366281_2112730',
        image: 'images/scored.png',
        tags: [],
        rating: 5,
        exclusive: false,
        terms: '18+. T&Cs apply.',
        wagering: '35x',
        minDeposit: '30$',
        maxBonus: '',
        casino: 'Scored',
        brandName: 'Scored',
        casinoId: 'scored-b281',
        order: 5
    },
    {
        id: '7',
        title: '300% up to $4750 + 100 Free Spins',
        description:
            '1st Deposit:100% up to $2500 +100 FS\n2nd Deposit:75% up to $1500\n3rd Deposit:125% up to $750',
        code: '',
        link: 'https://kngs.myloric.com/?mid=366282_2112739',
        image: 'images/kyngs.png',
        tags: [],
        rating: 5,
        exclusive: false,
        terms: '18+. T&Cs apply.',
        wagering: '35x',
        minDeposit: '30$',
        maxBonus: '',
        casino: 'Kyngs',
        brandName: 'Kyngs',
        casinoId: 'kyngs-b282',
        order: 6
    },
    {
        id: '8',
        title: '300% up to $10000 + 300 Free Spins',
        description:
            '1st Deposit:100% up to $3500  +100 FS\n2nd Deposit:100% up to $3000 +75 FS\n3rd Deposit:100% up to $3500 +125 FS.',
        code: '',
        link: 'https://jokj.myloric.com/?mid=366283_2112744',
        image: 'images/joker8.png',
        tags: [],
        rating: 5,
        exclusive: false,
        terms: '18+. T&Cs apply.',
        wagering: '35x',
        minDeposit: '30$',
        maxBonus: '',
        casino: 'Joker8',
        brandName: 'Joker8',
        casinoId: 'joker8-b283',
        order: 7
    },
    {
        id: '9',
        title: '250% up to $4,000 + 150 Free Spins',
        description:
            '1st Deposit:150% up to $1500  +50 FS\n2nd Deposit:50% up to $1000 +50 FS\n3rd Deposit:50% up to $1500 +50 FS.',
        code: '',
        link: 'https://vgso.virelon.com/?mid=366181_2112747',
        image: 'images/vegasino.png',
        tags: [],
        rating: 5,
        exclusive: false,
        terms: '18+. T&Cs apply.',
        wagering: '35x',
        minDeposit: '30$',
        maxBonus: '',
        casino: 'Vegasino',
        brandName: 'Vegasino',
        casinoId: 'vegasino-b284',
        order: 8
    },
    {
        id: '10',
        title: '300% up to $4750 + 100 Free Spins',
        description:
            '1st Deposit:100% up to $2500 +100 FS\n2nd Deposit:75% up to $1500\n3rd Deposit:125% up to $750',
        code: '',
        link: 'https://socr.virelon.com/?mid=366181_2112748',
        image: 'images/zoccer.png',
        tags: [],
        rating: 5,
        exclusive: false,
        terms: '18+. T&Cs apply.',
        wagering: '35x',
        minDeposit: '30$',
        maxBonus: '',
        casino: 'Zoccer',
        brandName: 'Zoccer',
        casinoId: 'zoccer-b285',
        order: 9
    },
    {
        id: '11',
        title: '250% up to $4,000 + 150 Free Spins',
        description:
            '1st Deposit:150% up to $1500  +50 FS\n2nd Deposit:50% up to $1000 +50 FS\n3rd Deposit:50% up to $1500 +50 FS.',
        code: '',
        link: 'https://grtw.virelon.com/?mid=366181_2112749',
        image: 'images/greatwin.png',
        tags: [],
        rating: 5,
        exclusive: false,
        terms: '18+. T&Cs apply.',
        wagering: '35x',
        minDeposit: '30$',
        maxBonus: '',
        casino: 'GreatWin',
        brandName: 'GreatWin',
        casinoId: 'greatwin-b286',
        order: 10
    },
    {
        id: '12',
        title: '300% up to $10000 + 300 Free Spins',
        description:
            '1st Deposit:100% up to $3500  +100 FS\n2nd Deposit:100% up to $3000 +75 FS\n3rd Deposit:100% up to $3500 +125 FS.',
        code: '',
        link: 'https://spnsy.lunostra.com/?mid=366182_2112751',
        image: 'images/spinsy.png',
        tags: [],
        rating: 5,
        exclusive: false,
        terms: '18+. T&Cs apply.',
        wagering: '35x',
        minDeposit: '30$',
        maxBonus: '',
        casino: 'Spinsy',
        brandName: 'Spinsy',
        casinoId: 'spinsy-b287',
        order: 11
    },
    {
        id: '13',
        title: '250% up to $4,000 + 150 Free Spins',
        description:
            '1st Deposit:150% up to $1500  +50 FS\n2nd Deposit:50% up to $1000 +50 FS\n3rd Deposit:50% up to $1500 +50 FS.',
        code: '',
        link: 'https://mfac.lunostra.com/?mid=366182_2112750',
        image: 'images/mafia.png',
        tags: [],
        rating: 5,
        exclusive: false,
        terms: '18+. T&Cs apply.',
        wagering: '35x',
        minDeposit: '30$',
        maxBonus: '',
        casino: 'Mafia',
        brandName: 'Mafia',
        casinoId: 'mafia-b288',
        order: 12
    },
    {
        id: '14',
        title: '300% up to $4750 + 100 Free Spins',
        description:
            '1st Deposit:100% up to $2500 +100 FS\n2nd Deposit:75% up to $1500\n3rd Deposit:125% up to $750',
        code: '',
        link: 'https://cshd.lunostra.com/?mid=366182_2112754',
        image: 'images/cashed.png',
        tags: [],
        rating: 5,
        exclusive: false,
        terms: '18+. T&Cs apply.',
        wagering: '35x',
        minDeposit: '30$',
        maxBonus: '',
        casino: 'Cashed',
        brandName: 'Cashed',
        casinoId: 'cashed-b289',
        order: 13
    },
    {
        id: '15',
        title: '250% up to $4,000 + 150 Free Spins',
        description:
            '1st Deposit:150% up to $1500  +50 FS\n2nd Deposit:50% up to $1000 +50 FS\n3rd Deposit:50% up to $1500 +50 FS.',
        code: '',
        link: 'https://csnl.lunostra.com/?mid=366182_2112757',
        image: 'images/casinoly.png',
        tags: [],
        rating: 5,
        exclusive: false,
        terms: '18+. T&Cs apply.',
        wagering: '35x',
        minDeposit: '30$',
        maxBonus: '',
        casino: 'Casinoly',
        brandName: 'Casinoly',
        casinoId: 'casinoly-b290',
        order: 14
    },
    {
        id: '16',
        title: '300% up to $10000 + 300 Free Spins',
        description:
            '1st Deposit:100% up to $3500  +100 FS\n2nd Deposit:100% up to $3000 +75 FS\n3rd Deposit:100% up to $3500 +125 FS.',
        code: '',
        link: 'https://pwb.lunostra.com/?mid=366182_2112758',
        image: 'images/powbet.png',
        tags: [],
        rating: 5,
        exclusive: false,
        terms: '18+. T&Cs apply.',
        wagering: '35x',
        minDeposit: '30$',
        maxBonus: '',
        casino: 'PowBet',
        brandName: 'PowBet',
        casinoId: 'powbet-b291',
        order: 15
    },
    {
        id: '17',
        title: '250% up to $4,000 + 150 Free Spins',
        description:
            '1st Deposit:150% up to $1500  +50 FS\n2nd Deposit:50% up to $1000 +50 FS\n3rd Deposit:50% up to $1500 +50 FS.',
        code: '',
        link: 'https://vplk.lunostra.com/?mid=366286_2112770',
        image: 'images/vipluck.png',
        tags: [],
        rating: 5,
        exclusive: false,
        terms: '18+. T&Cs apply.',
        wagering: '35x',
        minDeposit: '30$',
        maxBonus: '',
        casino: 'VIPLuck',
        brandName: 'VIPLuck',
        casinoId: 'vipluck-b292',
        order: 16
    }
    /* Sport Monsterwin — disabled
    ,{
        id: 'gbTSS3pRgDb2pR2PSXhK',
        title: 'Sport - 100% up to $150',
        description:
            '1. Single bets with odds of at least 2.00 settled as win / lose\n2. Multi-bets with odds of at least 1.50 per each selection settled as win / lose',
        code: '',
        link: 'https://mnsw.kronvax.com/?mid=366179_2112118',
        image: 'images/monsterwin.png',
        tags: ['Sports'],
        rating: 5,
        exclusive: false,
        terms: '18+. T&Cs apply.',
        wagering: '6x',
        minDeposit: '$30',
        maxBonus: '',
        casino: 'Monsterwin ',
        brandName: 'Monsterwin ',
        casinoId: 'PV8jUsLbBuTl0WWCwQ7f',
        order: 5
    }
    */
];
